'use client'

import { useState, useEffect, useCallback } from 'react'
import { useSession } from 'next-auth/react'
import { Loader2, RefreshCw, TrendingUp, Zap, Globe } from 'lucide-react'
import toast from 'react-hot-toast'
import PortfolioDonut from '@/components/charts/PortfolioDonut'
import { formatINR } from '@/lib/utils/formatCurrency'
import type { PortfolioSuggestion, MacroInsight } from '@/types'

const RISK_QUESTIONS = [
  {
    question: "If your investment drops 30% overnight, you would...",
    options: [{ label: "Sell everything", score: 1 }, { label: "Wait and watch", score: 3 }, { label: "Buy more — it's a discount!", score: 5 }],
  },
  {
    question: "When do you need this money?",
    options: [{ label: "Within 1 year", score: 1 }, { label: "In 1-3 years", score: 3 }, { label: "5+ years away", score: 5 }],
  },
  {
    question: "How do you describe your investing style?",
    options: [{ label: "Safety first always", score: 1 }, { label: "Balanced approach", score: 3 }, { label: "High risk high reward", score: 5 }],
  },
]

const ASSET_BADGE: Record<string, string> = {
  equity: 'bg-brand-muted text-brand border border-brand/20',
  debt: 'bg-blue-500/10 text-blue-400 border border-blue-500/20',
  gold: 'bg-amber-500/10 text-amber-400 border border-amber-500/20',
  cash: 'bg-border text-text-muted border border-border',
}

const RISK_LABELS: Record<number, string> = {
  1: 'Conservative', 2: 'Moderately Conservative', 3: 'Balanced', 4: 'Moderately Aggressive', 5: 'Aggressive',
}

export default function PortfolioPage() {
  const { data: session, status } = useSession()
  const [portfolio, setPortfolio] = useState<PortfolioSuggestion | null>(null)
  const [macro, setMacro] = useState<MacroInsight | null>(null)
  const [loading, setLoading] = useState(true)
  const [generating, setGenerating] = useState(false)
  const [riskAnswers, setRiskAnswers] = useState<number[]>([])
  const [showQuestionnaire, setShowQuestionnaire] = useState(false)

  const userId = session?.user?.id
  const income = session?.user?.monthly_income ?? 50000
  const sessionRisk = session?.user?.risk_appetite ?? 3

  const loadPortfolio = useCallback(async () => {
    if (!userId) return
    setLoading(true)
    try {
      const [dashRes, macroRes] = await Promise.all([
        fetch(`/api/dashboard?user_id=${userId}`),
        fetch('/api/macro'),
      ])
      if (dashRes.ok) {
        const data = await dashRes.json()
        if (data.portfolio) setPortfolio(data.portfolio)
      }
      if (macroRes.ok) setMacro(await macroRes.json())
    } catch {
      toast.error('Failed to load portfolio')
    } finally {
      setLoading(false)
    }
  }, [userId])

  useEffect(() => {
    if (status === 'authenticated') loadPortfolio()
  }, [status, loadPortfolio])

  const riskScore = riskAnswers.length === 3
    ? Math.round(riskAnswers.reduce((a, b) => a + b, 0) / 3)
    : sessionRisk

  async function generatePortfolio(riskOverride?: number) {
    if (!userId) return
    setGenerating(true)
    try {
      const res = await fetch('/api/portfolio-suggest', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          user_id: userId,
          risk_score: riskOverride ?? riskScore,
          monthly_income: income,
        }),
      })
      if (!res.ok) throw new Error()
      const data = await res.json()
      setPortfolio(data)
      setShowQuestionnaire(false)
      toast.success('Portfolio generated by Claude!')
    } catch {
      toast.error('Failed to generate portfolio')
    } finally {
      setGenerating(false)
    }
  }

  if (status === 'loading' || loading) {
    return (
      <div className="p-6 md:p-8 space-y-4">
        {[...Array(3)].map((_, i) => (
          <div key={i} className="animate-pulse bg-surface-raised rounded-2xl h-36 border border-border" />
        ))}
      </div>
    )
  }

  return (
    <div className="p-6 md:p-8">
      <div className="flex items-center justify-between mb-6">
        <div>
          <h1 className="text-xl font-bold text-text-base">Portfolio</h1>
          <p className="text-xs text-text-muted mt-0.5 flex items-center gap-1.5">
            <Zap size={12} className="text-purple-400" />
            SEBI-aligned allocation by Claude · Macro context by Gemini
          </p>
        </div>
        <button
          onClick={() => setShowQuestionnaire(!showQuestionnaire)}
          disabled={generating}
          className="flex items-center gap-2 bg-surface-raised border border-border rounded-xl px-4 py-2 text-sm text-text-muted hover:border-brand/30 hover:text-text-base transition-all"
        >
          <RefreshCw size={14} className={generating ? 'animate-spin' : ''} />
          {portfolio ? 'Re-assess' : 'Generate'}
        </button>
      </div>

      {/* Macro context strip */}
      {macro && (
        <div className="bg-surface-raised border border-blue-500/20 rounded-2xl p-4 mb-5 flex items-start gap-3">
          <Globe size={16} className="text-blue-400 shrink-0 mt-0.5" />
          <div className="flex-1 min-w-0">
            <div className="flex items-center gap-2 mb-1">
              <span className="text-xs font-semibold text-blue-400">Gemini Macro Signal</span>
              <span className={`text-[10px] font-bold rounded-full px-2 py-0.5 ${macro.sentiment === 'bullish' ? 'bg-brand-muted text-brand' : macro.sentiment === 'cautious' ? 'bg-orange-500/10 text-orange-400' : 'bg-border text-text-muted'}`}>
                {macro.sentiment.toUpperCase()}
              </span>
            </div>
            <p className="text-xs text-text-muted">{macro.rbi_note} — <span className="text-brand font-medium">{macro.action_tip}</span></p>
          </div>
        </div>
      )}

      {/* Risk questionnaire */}
      {showQuestionnaire && (
        <div className="bg-surface-raised border border-border rounded-2xl p-6 mb-5">
          <div className="flex items-center gap-2 mb-4">
            <TrendingUp size={16} className="text-purple-400" />
            <h2 className="text-base font-bold text-text-base">Risk Assessment</h2>
            <span className="text-[10px] bg-purple-500/10 text-purple-400 border border-purple-500/20 rounded-full px-2 py-0.5 font-semibold uppercase">Claude AI</span>
          </div>
          {RISK_QUESTIONS.map((q, qi) => (
            <div key={qi} className="mb-4">
              <p className="text-sm font-medium text-text-base mb-2">{q.question}</p>
              <div className="flex flex-col gap-2">
                {q.options.map((opt) => {
                  const selected = riskAnswers[qi] === opt.score
                  return (
                    <button
                      key={opt.score}
                      onClick={() => { const a = [...riskAnswers]; a[qi] = opt.score; setRiskAnswers(a) }}
                      className={`text-left px-4 py-2.5 rounded-xl text-sm border transition-colors ${selected ? 'border-brand bg-brand-muted text-brand font-medium' : 'border-border text-text-muted hover:border-brand/30 hover:text-text-base'}`}
                    >
                      {opt.label}
                    </button>
                  )
                })}
              </div>
            </div>
          ))}
          {riskAnswers.length === 3 && (
            <div className="bg-brand-muted border border-brand/20 rounded-xl p-3 mb-4 text-center">
              <p className="text-sm font-bold text-brand">Risk score: {riskScore}/5 — {RISK_LABELS[riskScore]}</p>
            </div>
          )}
          <button
            onClick={() => generatePortfolio(riskAnswers.length === 3 ? riskScore : undefined)}
            disabled={generating}
            className="w-full bg-brand hover:bg-brand-dim text-[#0A0A0A] font-bold rounded-xl py-3 text-sm flex items-center justify-center gap-2 disabled:opacity-50"
          >
            {generating ? <><Loader2 size={14} className="animate-spin" />Generating with Claude...</> : 'Generate AI Portfolio →'}
          </button>
        </div>
      )}

      {/* No portfolio state */}
      {!portfolio && !showQuestionnaire && (
        <div className="text-center py-16 bg-surface-raised border border-border rounded-2xl">
          <TrendingUp size={40} className="text-text-faint mx-auto mb-4" />
          <p className="text-text-base font-semibold mb-1">No portfolio yet</p>
          <p className="text-sm text-text-muted mb-5">Answer 3 questions and Claude will generate a SEBI-aligned portfolio with real Indian mutual funds.</p>
          <button onClick={() => setShowQuestionnaire(true)} className="bg-brand text-[#0A0A0A] font-bold rounded-xl px-6 py-3 text-sm flex items-center gap-2 mx-auto">
            <TrendingUp size={16} /> Generate My Portfolio
          </button>
        </div>
      )}

      {/* Portfolio display */}
      {portfolio && !showQuestionnaire && (
        <div className="space-y-5">
          {/* Allocation chart */}
          <div className="grid grid-cols-1 md:grid-cols-2 gap-5">
            <div className="bg-surface-raised border border-border rounded-2xl p-6">
              <p className="text-sm font-semibold text-text-base mb-4">Asset Allocation</p>
              <PortfolioDonut allocation={portfolio.allocation} />
              <div className="grid grid-cols-2 gap-2 mt-4">
                {Object.entries(portfolio.allocation).map(([k, v]) => (
                  <div key={k} className={`rounded-xl px-3 py-2 text-xs font-semibold flex items-center justify-between ${ASSET_BADGE[k]}`}>
                    <span className="capitalize">{k}</span>
                    <span>{v}%</span>
                  </div>
                ))}
              </div>
            </div>

            <div className="bg-surface-raised border border-border rounded-2xl p-6">
              <div className="flex items-center gap-2 mb-3">
                <Zap size={15} className="text-purple-400" />
                <p className="text-sm font-semibold text-text-base">AI Reasoning</p>
                <span className="text-[10px] bg-purple-500/10 text-purple-400 border border-purple-500/20 rounded-full px-2 py-0.5 font-semibold uppercase">Claude</span>
              </div>
              <p className="text-sm text-text-muted leading-relaxed mb-4">{portfolio.reasoning}</p>
              <div className="bg-brand-muted border border-brand/20 rounded-xl p-3 text-center">
                <p className="text-xs text-text-muted mb-0.5">Recommended Monthly SIP</p>
                <p className="text-2xl font-bold text-brand">{formatINR(portfolio.sip_amount)}</p>
              </div>
            </div>
          </div>

          {/* Instruments */}
          <div className="bg-surface-raised border border-border rounded-2xl p-5">
            <p className="text-sm font-semibold text-text-base mb-4">Recommended Instruments</p>
            <div className="grid grid-cols-1 md:grid-cols-2 gap-3">
              {Object.entries(portfolio.instruments as Record<string, string[]>).map(([asset, funds]) => (
                <div key={asset} className="bg-surface border border-border rounded-xl p-4">
                  <p className={`text-xs font-bold uppercase mb-2 ${ASSET_BADGE[asset]?.includes('brand') ? 'text-brand' : ''}`}>
                    {asset} ({portfolio.allocation[asset as keyof typeof portfolio.allocation]}%)
                  </p>
                  <ul className="space-y-1">
                    {(Array.isArray(funds) ? funds : []).map((f, i) => (
                      <li key={i} className="text-xs text-text-muted flex items-center gap-1.5">
                        <span className="w-1 h-1 rounded-full bg-text-faint inline-block shrink-0" />
                        {f}
                      </li>
                    ))}
                  </ul>
                </div>
              ))}
            </div>
          </div>

          {/* Macro note */}
          {portfolio.macro_note && (
            <div className="bg-blue-500/5 border border-blue-500/20 rounded-2xl p-4 flex gap-3">
              <Globe size={16} className="text-blue-400 shrink-0 mt-0.5" />
              <div>
                <p className="text-xs font-semibold text-blue-400 mb-1">Macro Context</p>
                <p className="text-xs text-text-muted leading-relaxed">{portfolio.macro_note}</p>
              </div>
            </div>
          )}
        </div>
      )}
    </div>
  )
}
